name: Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: List files
      run: ls -la
    - name: Grant execute permission
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleDebug
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: app/build/
