name: Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Gradle
      run: |
        GRADLEW_FILE=$(find . -name "gradlew" -type f | head -n 1)
        if [ -z "$GRADLEW_FILE" ]; then
          echo "Error: gradlew not found!"
          exit 1
        fi
        echo "Found gradlew at: $GRADLEW_FILE"
        chmod +x "$GRADLEW_FILE"
        "$GRADLEW_FILE" assembleDebug --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/app-debug.apk"
